# -*- coding: utf-8 -*-
"""programmers다음에올숫자.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19tqFIyKsT2t0rfuqv3g_-y2_cmcHXsmw

python3 lv0 다음에 올 숫자
"""

def solution(common):
    num = common[1] - common[0]    # 문제에서 등차수열 혹은 등비수열 밖에 없으므로 제일 작은 두개의 수만 뺌
    if common[1] + num == common[2]:
        answer = common[len(common)-1] + num
    else:
        num = common[1] // common[0]    
        answer = common[len(common)-1] * num
    return answer