# -*- coding: utf-8 -*-
"""python300_251~.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-zYiIRUsoT1Fl5YCscR0NF7VSEwS2dzl

CLASS문
"""

class Human:
    def __init__(self,name,age,sex):

        self.name = name
        self.age = age
        self.sex = sex
        

    def who(self):
        print(f'이름: {self.name}, 나이: {self.age}, 성별: {self.sex}')

    def setInfo(self,name,age,sex):
        self.name = name
        self.age = age
        self.sex = sex

    def __del__(self): # 클래스 소멸자  
        print('나의 죽음을 알리지 말라') 


per = Human("모름", 0, "모름")
per.who()
per.setInfo("유수정", 28, "여자")
per.who()
del per #소멸자는 띄우고 사용

class OMG :
    def print() :
        print("Oh my god")


mystock = OMG()
# mystock.print() == OMG.print(mystock) #둘다 안됨 print()에는 self가 없기때문에 에러가 남

class Stock:
    def __init__(self, company, code):
        self.company=company
        self.code=code

    def set_company(self, company):
        self.company = company

    def set_code(self, code):
        self.code = code

    def get_company(self):
        return self.company

    def get_code(self):
        return self.code

a= Stock(None,None)
a.set_company('삼전')
a.set_code('005930')
print(a.company)
print(a.code)
삼성 = Stock("삼성전자", "005930")
print(삼성.get_company())
print(삼성.get_code())

class Stock:
    def __init__(self,name,code,PER,PBR,qoekd): 
        self.name = name
        self.code = code
        self.PER = float(PER)
        self.PBR = float(PBR)
        self.qoekd = float(qoekd)

    def set_name(self, name):
        self.name = name
    def set_code(self, code):
        self.code = code
    def set_PER(self, PER):
        self.PER = PER
    def set_PBR(self, PBR):
        self.PBR = PBR
    def set_qoekd(self, qoekd):
        self.qoekd = qoekd   
    
삼성 = Stock("삼성전자", "005930", 15.79, 1.33, 2.83)
print(삼성.qoekd)

삼성.set_PER(12.75)
print(삼성.PER)

li = []
Samsung = Stock("삼성전자", "005930", 15.79, 1.33, 2.83)
Hy = Stock('현대차','005380', 8.70, 0.35, 4.27)
LG = Stock('LG전자', '066570', 317.34, 0.69, 1.37)

li.append(Samsung)
li.append(Hy)
li.append(LG)

for i in li:
    print(i.code, i.PER) # i에 Stock클레스의 객체를 바인딩 하기때문에